inherit_from: .rubocop_todo.yml

Gemspec/OrderedDependencies:
  Exclude:
    - 'railway_operation.gemspec'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'bin/console'

Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
